# Generated by Django 6.0.1 on 2026-03-09 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id_chat', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'chats',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('order_created_at', models.DateTimeField(auto_now_add=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Ожидание получения'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='pending', max_length=50)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='ProductTypes',
            fields=[
                ('id_producttype', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'producttypes',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_role', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Tovars',
            fields=[
                ('id_tovar', models.AutoField(primary_key=True, serialize=False)),
                ('tovar_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tovars',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent_category', models.ForeignKey(blank=True, db_column='parent_category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appip.categories')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ChatSync',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_sync_at', models.DateTimeField(auto_now=True)),
                ('site_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_syncs', to='appip.chats')),
            ],
            options={
                'verbose_name': 'Синхронизация чата',
                'verbose_name_plural': 'Синхронизации чатов',
                'db_table': 'chat_sync',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id_orderitem', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('price_at_time_of_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='pending', max_length=50)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='appip.orders')),
            ],
            options={
                'db_table': 'orderitems',
            },
        ),
        migrations.AddField(
            model_name='chats',
            name='order',
            field=models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appip.orders'),
        ),
        migrations.CreateModel(
            name='ProductItems',
            fields=[
                ('id_productitem', models.AutoField(primary_key=True, serialize=False)),
                ('item_data', models.TextField()),
                ('item_type', models.CharField(choices=[('activation_key', 'Ключ активации'), ('account', 'Аккаунт (логин:пароль)'), ('instruction', 'Инструкция/текст'), ('file', 'Файл для скачивания')], default='activation_key', max_length=50)),
                ('is_sold', models.BooleanField(default=False)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(blank=True, db_column='order_item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appip.orderitems')),
            ],
            options={
                'db_table': 'productitems',
            },
        ),
        migrations.AddField(
            model_name='orderitems',
            name='product_item',
            field=models.ForeignKey(blank=True, db_column='product_item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appip.productitems'),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('main_image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('is_auto_delivery', models.BooleanField(default=False)),
                ('auto_delivery_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appip.categories')),
                ('product_type', models.ForeignKey(db_column='product_type_id', on_delete=django.db.models.deletion.CASCADE, to='appip.producttypes')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.AddField(
            model_name='productitems',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='appip.products'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='appip.products'),
        ),
        migrations.AddField(
            model_name='chats',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appip.products'),
        ),
        migrations.CreateModel(
            name='ProductsTovars',
            fields=[
                ('id_producttovar', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='appip.products')),
                ('tovar', models.ForeignKey(db_column='tovar_id', on_delete=django.db.models.deletion.CASCADE, to='appip.tovars')),
            ],
            options={
                'db_table': 'productstovars',
                'unique_together': {('product', 'tovar')},
            },
        ),
        migrations.AddField(
            model_name='products',
            name='tovars',
            field=models.ManyToManyField(related_name='products', through='appip.ProductsTovars', to='appip.tovars'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='tovar',
            field=models.ForeignKey(blank=True, db_column='tovar_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appip.tovars'),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.EmailField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('avatar_url', models.CharField(blank=True, max_length=500, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seller_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='appip.roles')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('register', 'Регистрация'), ('view_product', 'Просмотр товара'), ('add_to_cart', 'Добавление в корзину'), ('remove_from_cart', 'Удаление из корзины'), ('add_to_wishlist', 'Добавление в вишлист'), ('remove_from_wishlist', 'Удаление из вишлиста'), ('create_order', 'Создание заказа'), ('add_review', 'Добавление отзыва'), ('edit_review', 'Редактирование отзыва'), ('delete_review', 'Удаление отзыва'), ('update_profile', 'Обновление профиля'), ('change_password', 'Смена пароля'), ('download_receipt', 'Скачивание чека'), ('search', 'Поиск'), ('add_product', 'Добавление товара'), ('edit_product', 'Редактирование товара'), ('delete_product', 'Удаление товара'), ('send_message', 'Отправка сообщения'), ('deposit', 'Пополнение баланса'), ('withdrawal', 'Вывод средств'), ('admin_action', 'Действие администратора'), ('manager_action', 'Действие менеджера')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('additional_data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='appip.users')),
            ],
            options={
                'db_table': 'useractivitylogs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id_transaction', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Пополнение'), ('withdrawal', 'Вывод'), ('purchase', 'Покупка'), ('sale', 'Продажа'), ('refund', 'Возврат')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('completed', 'Завершено'), ('failed', 'Неудачно'), ('cancelled', 'Отменено')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appip.orders')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='appip.users')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='TelegramManager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_chat_id', models.CharField(max_length=100, unique=True)),
                ('telegram_username', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_connections', to='appip.users')),
            ],
            options={
                'verbose_name': 'Telegram менеджер',
                'verbose_name_plural': 'Telegram менеджеры',
                'db_table': 'telegram_managers',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='seller',
            field=models.ForeignKey(db_column='seller_id', on_delete=django.db.models.deletion.CASCADE, to='appip.users'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='appip.users'),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id_message', models.AutoField(primary_key=True, serialize=False)),
                ('message_text', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(db_column='chat_id', on_delete=django.db.models.deletion.CASCADE, to='appip.chats')),
                ('sender', models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, to='appip.users')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['sent_at'],
            },
        ),
        migrations.AddField(
            model_name='chats',
            name='buyer',
            field=models.ForeignKey(db_column='buyer_id', on_delete=django.db.models.deletion.CASCADE, related_name='buyer_chats', to='appip.users'),
        ),
        migrations.AddField(
            model_name='chats',
            name='seller',
            field=models.ForeignKey(db_column='seller_id', on_delete=django.db.models.deletion.CASCADE, related_name='seller_chats', to='appip.users'),
        ),
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id_productcategory', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='appip.categories')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='appip.products')),
            ],
            options={
                'db_table': 'productcategories',
                'unique_together': {('product', 'category')},
            },
        ),
        migrations.CreateModel(
            name='SellerReviews',
            fields=[
                ('id_sellerreview', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appip.orders')),
                ('buyer', models.ForeignKey(db_column='buyer_id', on_delete=django.db.models.deletion.CASCADE, related_name='buyer_reviews', to='appip.users')),
                ('seller', models.ForeignKey(db_column='seller_id', on_delete=django.db.models.deletion.CASCADE, related_name='seller_reviews', to='appip.users')),
            ],
            options={
                'db_table': 'sellerreviews',
                'unique_together': {('buyer', 'seller')},
            },
        ),
        migrations.CreateModel(
            name='ProductReviews',
            fields=[
                ('id_review', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='appip.products')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='appip.users')),
            ],
            options={
                'db_table': 'productreviews',
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ManagerChats',
            fields=[
                ('id_manager_chat', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('chat', models.ForeignKey(blank=True, db_column='chat_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appip.chats')),
                ('manager', models.ForeignKey(db_column='manager_id', on_delete=django.db.models.deletion.CASCADE, related_name='manager_chats', to='appip.users')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_manager_chats', to='appip.users')),
            ],
            options={
                'verbose_name': 'Чат менеджера',
                'verbose_name_plural': 'Чаты менеджера',
                'db_table': 'managerchats',
                'unique_together': {('manager', 'user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='chats',
            unique_together={('product', 'buyer', 'seller')},
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id_cart', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='appip.products')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='appip.users')),
            ],
            options={
                'db_table': 'cart',
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Wishlists',
            fields=[
                ('id_wishlist', models.AutoField(primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='appip.products')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='appip.users')),
            ],
            options={
                'db_table': 'wishlists',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
