# Generated by Django 6.0.1 on 2026-03-15 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appip', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegrammanager',
            options={'verbose_name': 'Менеджер мессенджера', 'verbose_name_plural': 'Менеджеры мессенджеров'},
        ),
        migrations.AddField(
            model_name='telegrammanager',
            name='vk_peer_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegrammanager',
            name='vk_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='telegrammanager',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_connections', to='appip.users'),
        ),
        migrations.AlterField(
            model_name='telegrammanager',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='telegrammanager',
            table='messenger_managers',
        ),
    ]
