# Generated by Django 6.0.1 on 2026-04-19 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appip', '0003_promocodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='dispute_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='dispute_resolution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='dispute_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='dispute_resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to='appip.users'),
        ),
        migrations.AddField(
            model_name='orders',
            name='disputed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
