# Generated by Django 6.0.1 on 2026-04-19 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appip', '0004_orders_dispute_reason_orders_dispute_resolution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='dispute_reason',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='dispute_resolution',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='dispute_resolved_at',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='dispute_resolved_by',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='disputed_at',
        ),
    ]
