# Generated by Django 6.0.1 on 2026-04-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appip', '0005_remove_orders_dispute_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='dispute_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='dispute_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='dispute_resolution_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='dispute_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='dispute_status',
            field=models.CharField(choices=[('none', 'Нет спора'), ('open', 'Спор открыт'), ('resolved', 'Спор разрешен'), ('rejected', 'В споре отказано')], default='none', max_length=50),
        ),
        migrations.AlterModelTable(
            name='orders',
            table=None,
        ),
    ]
