# Generated by Django 6.0.1 on 2026-04-19 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appip', '0006_orders_dispute_created_at_orders_dispute_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='dispute_created_at',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='dispute_reason',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='dispute_resolution_note',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='dispute_resolved_at',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='dispute_status',
        ),
        migrations.AlterModelTable(
            name='orders',
            table='orders',
        ),
    ]
